"""Initial migration with Beer and User models

Revision ID: 384bceb4aa18
Revises: 
Create Date: 2025-08-22 02:13:58.739461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384bceb4aa18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beer_type', sa.String(length=80), nullable=False),
    sa.Column('style', sa.String(length=80), nullable=False),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ibu', sa.Float(), nullable=False),
    sa.Column('abv', sa.Float(), nullable=False),
    sa.Column('card_action', sa.Text(), nullable=False),
    sa.Column('hops', sa.Integer(), nullable=False),
    sa.Column('grains', sa.Integer(), nullable=False),
    sa.Column('yeast', sa.Integer(), nullable=False),
    sa.Column('water', sa.Integer(), nullable=False),
    sa.Column('special', sa.Integer(), nullable=False),
    sa.Column('group_action', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('beer')
    # ### end Alembic commands ###
