name: CI/CD

on:
  push:
    branches:
      - master # Trigger on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Grant write permission for packages (GHCR)

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Add Docker setup for building and pushing
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest # Tag with GHCR path and 'latest'
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # You can add more steps here for testing, linting, etc.
    # For example:
    # - name: Run tests
    #   run: pytest
    # - name: Run linter
    #   run: flake8 .

    - name: Build (Placeholder for any build steps)
      run: echo "No specific build steps for this Flask app, Render handles deployment."

    # No explicit deployment step here, as Render handles it via Git integration.
    # If you needed to trigger a deploy hook via Render API, it would go here.
